site_name: Matcher - Chaveamento de torneios
theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate

nav:
  - Declaração do escopo: escopo.md
  - Visão do produto e do projeto: visao-produto-projeto.md
  - Documento de arquitetura: documento-arquitetura.md
  - Atas de reunião:
      - Reunião de 12 de setembro de 2023: ata-reuniao-12-set.md
  - Sprints:
      - Sprint 1: 
        - Planning: sprints/sprint-1/s1-planning.md
        - Dailies: sprints/sprint-1/s1-dailies.md
        - Review e retrospective: sprints/sprint-1/s1-review-retrospective.md

