site_name: Matcher - Chaveamento de torneios
theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate

nav:
  - Declaração do escopo: escopo.md
  - Visão do produto e do projeto: visao-produto-projeto.md
  - Documento de arquitetura: documento-arquitetura.md
  - Atas de reunião:
      - Reunião de 12 de setembro de 2023: ata-reuniao-12-set.md
  - Sprints:
      - Sprint 1: 
        - Planning: sprints/sprint-1/s1-planning.md
        - Dailies: sprints/sprint-1/s1-dailies.md
        - Review e retrospective: sprints/sprint-1/s1-review-retrospective.md
      - Sprint 2: 
        - Planning: sprints/sprint-2/s2-planning.md
        - Dailies: sprints/sprint-2/s2-dailies.md
        - Review e retrospective: sprints/sprint-2/s2-review-retrospective.md
      - Sprint 3: 
        - Planning: sprints/sprint-3/s3-planning.md
        - Dailies: sprints/sprint-3/s3-dailies.md
        - Review e retrospective: sprints/sprint-3/s3-review-retrospective.md
      - Sprint 4: 
        - Planning: sprints/sprint-4/s4-planning.md
        - Dailies: sprints/sprint-4/s4-dailies.md
        - Review e retrospective: sprints/sprint-4/s4-review-retrospective.md
      - Sprint 5: 
        - Planning: sprints/sprint-5/s5-planning.md
        - Dailies: sprints/sprint-5/s5-dailies.md
        - Review e retrospective: sprints/sprint-5/s5-review-retrospective.md
      - Sprint 6: 
        - Planning: sprints/sprint-6/s6-planning.md
        - Dailies: sprints/sprint-6/s6-dailies.md
        - Review e retrospective: sprints/sprint-6/s6-review-retrospective.md
