version: '3'

services:
  database:
    image: postgres
    container_name: Matcher_DB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=develop_usermatcher
      - POSTGRES_PASSWORD=matcher_developpass
      - POSTGRES_DB=matcher_develop
    volumes:
      - pgdata:/data/postgres
  app:
    container_name: Matcher_APP
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
